### ISSUE TITLE
ImportError: No module named flashcards

### ISSUE THREAD

**Issue by chrisspen** [Woile/flashcards#1]
I'm unable to install and run this package following the README's instructions.

This is what I ran:

    sudo -H pip install python-flashcards
    flashcards --ordered mycards.yaml

which gives me the error:

    Traceback (most recent call last):
      File "/usr/local/bin/flashcards", line 9, in <module>
        load_entry_point('python-flashcards==0.1.0', 'console_scripts', 'flashcards')()
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
        return get_distribution(dist).load_entry_point(group, name)
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
        return ep.load()
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2229, in load
        return self.resolve()
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
      File "/usr/local/lib/python2.7/dist-packages/flashcards/cli.py", line 18, in <module>
        from flashcards.flashcards import start
    ImportError: No module named flashcards

I also tried installing into a virtualenv, but that gets me the same error.

If I launch a Python interpreter and manually call `from flashcards.flashcards import start`, it works fine, so my guess it's a problem with your bin script and your package structure.

You made the design mistake of calling your package and sub-module the same name, i.e. "flashcards". When your `cli.py` runs, it tries to import `flashcards.flashcards`. However, by default, Python looks in the local directory first, where it sees the module "flashcards" and imports it, and then looks up the sub-module "flashcards", which of course doesn't exist there.

You could probably fix this in one of three ways:

1. Re-name your "flashcards" module something else, so it doesn't conflict with your package name (the preferred option).
2. Try munging `sys.path` to make Python check the global package locations first.
3. Wrap the `from flashcards.flashcards import start` inside a try/except and do `from flashcards import start` if the import fails.

**Comment by woile** [comment]
Hi @chrisspen, thank you for the feedback!! 

First I can see that you are using python2.7, it requires python3, I'll try to make it compatible with python2.7 in the next weeks, I might've made a mistake when uploading to pip, but the changes to make it compatible shouldn't be much. Can you try installing it with python3 and tell me if this error still happens? I've just tried with a new virtualenv with py3 and it worked with no problems.

Thank you again!

**Comment by woile** [comment]
Support for python2.7 added
